Import( 'env' )
Import( 'compmap' )
import profiles

env.Append( LINKFLAGS = ['-framework', 'CoreFoundation', '-framework', 'Security'] )

profiles.DynamicLibrary(
        'rpHCP_BulkCollector',
        profiles.GitInfo(),
        LIBS = 'm'
        ).Target(
            env,
            Glob( '*.c' ),
            compmap,
            'rpHostCommonPlatformIFaceLib',
            'cryptoLib',
            'networkLib',
            'Os',
            'libRestOutput',
            'kernelAcquisitionLib',
            )


# EOF
